### ISSUE TITLE
Error creating mixin

### ISSUE THREAD

**Issue by AmibeSkyfy16** [KosmX/bendy-lib#26]
I have this error

Version
1.18.1
Fabric loader 0.12.12

java.lang.RuntimeException: Error creating Mixin config bendylib.mixins.json for mod bendy-lib
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config bendylib.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'bendylib.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by KosmX** [comment]
This error message won't be enough.  
Try loading your game again, if that doesn't help, please send a full crash report.

**Comment by LufatZ** [comment]
when i export my modpack with curseforge and import it again and start it the first time i get the same error. On the second start it works fine... the same applies when i have an empty profile with only emotecraft for 1.17.1 and start it for the first time.

in the first case:
![image](https://user-images.githubusercontent.com/86516373/158029154-7cd5d490-e789-479a-b990-84eeedca1cc7.png)

in the second case:
![image](https://user-images.githubusercontent.com/86516373/158028967-3b0b03e0-4039-41c7-a2a5-844811c4542a.png)

**Comment by KosmX** [comment]
I'll look into it again.
Can you tell me what modpack did you use?

**Comment by LufatZ** [comment]
my modpack is DayOfMind. but as I said. For me the error also occurs with an empty instance where only emotecraft is installed

**Comment by LufatZ** [comment]
Have you found out what is causing the error? Or if it can be fixed soon?

**Comment by KosmX** [comment]
I'm not sure if it is a bug in Emotecraft or bendy-lib.  
I'll check Fabric loader, this fails too early.
